name: CI/CD for Node.js Docker App

on:
  push:
    branches:
      - main  # Triggers workflow on push to the "main" branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # This will run on an Ubuntu machine

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub secrets

      # Step 3: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t jaydip54/cicd:latest .  # Replace with your Docker Hub username
          docker push jaydip54/cicd:latest  # Replace with your Docker Hub username

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # This step will run only after the build-and-push job is successful

    steps:
      # Step 4: Trigger Render deployment using a deploy hook (GET request)
      - name: Trigger Render Deploy Hook
        if: success()  # Ensure this only runs if previous steps succeed
        run: |
          curl -X GET "https://api.render.com/deploy/srv-ct7e3l5ds78s73d50fcg?key=pKl4qTOvXD8"  # Use your Render deploy hook key
